# Generated by Django 4.2.2 on 2023-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainMsg', models.CharField(max_length=2000)),
                ('MailingAddress', models.EmailField(max_length=254)),
                ('Choice', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('PresentDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
