# Generated by Django 4.2.2 on 2023-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildata',
            name='Choice',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='maildata',
            name='MailingAddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='maildata',
            name='MainMsg',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
