# Generated by Django 4.2.2 on 2023-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_alter_maildata_presentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildata',
            name='PresentDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='PresentDate'),
        ),
    ]
