# Generated by Django 4.2.2 on 2023-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_alter_maildata_presentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildata',
            name='PresentDate',
            field=models.DateField(null=True, verbose_name='PresentDate'),
        ),
    ]
