# Generated by Django 4.2.2 on 2023-07-10 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_alter_maildata_presentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maildata',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='maildata',
            name='MainMsg',
        ),
        migrations.RemoveField(
            model_name='maildata',
            name='PresentDate',
        ),
        migrations.AddField(
            model_name='maildata',
            name='MailMessage',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maildata',
            name='MailingAddress',
            field=models.EmailField(max_length=254),
        ),
    ]
