# Generated by Django 4.2.2 on 2023-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_maildata_mailingcreationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildata',
            name='MailStatus',
            field=models.BooleanField(null=True),
        ),
    ]
