# Generated by Django 4.2.2 on 2023-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0008_maildata_mailstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildata',
            name='MailMessage',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
